In [22]:
import numpy as np
import pandas as pd

In [23]:
url = 'https://raw.githubusercontent.com/fabiommendes/desenvolvimento-de-software/master/dados/pnad2012.csv'
data = pd.read_csv(url, index_col=0)

In [24]:
data

,education,income,income_work,income_rent,income_capital,race,gender,weight
0,15.0,3000.0,3000.0,NaN,NaN,16,1,246.0
1,15.0,3000.0,3000.0,NaN,NaN,16,2,246.0
2,15.0,1100.0,1100.0,NaN,NaN,16,2,246.0
3,14.0,1100.0,1100.0,NaN,NaN,16,2,246.0
4,15.0,460.0,NaN,460.0,460.0,16,2,246.0
5,15.0,10000.0,10000.0,NaN,NaN,2,1,246.0
6,15.0,500.0,500.0,NaN,NaN,4,2,247.0
7,0.0,622.0,NaN,NaN,NaN,4,2,246.0
8,11.0,622.0,622.0,NaN,NaN,2,2,247.0
9,15.0,1200.0,1200.0,NaN,NaN,4,1,246.0
10,4.0,NaN,NaN,NaN,NaN,2,2,246.0
11,8.0,1000.0,1000.0,NaN,NaN,4,1,246.0
12,11.0,NaN,NaN,NaN,NaN,4,2,247.0
13,11.0,1200.0,1200.0,NaN,NaN,4,2,246.0
14,6.0,NaN,NaN,NaN,NaN,4,1,246.0
15,0.0,NaN,NaN,NaN,NaN,4,1,246.0
16,8.0,622.0,NaN,NaN,NaN,4,2,247.0
17,8.0,7000.0,7000.0,NaN,NaN,4,1,246.0
18,8.0,NaN,NaN,NaN,NaN,4,2,247.0
19,15.0,1700.0,1700.0,NaN,NaN,4,1,246.0
20,13.0,NaN,NaN,NaN,NaN,16,1,246.0
21,10.0,5000.0,5000.0,NaN,NaN,4,1,246.0
22,14.0,NaN,NaN,NaN,NaN,2,2,246.0
23,9.0,NaN,NaN,NaN,NaN,4,1,246.0
24,14.0,2000.0,2000.0,NaN,NaN,16,1,247.0
25,0.0,NaN,NaN,NaN,NaN,4,2,246.0
26,4.0,622.0,622.0,NaN,NaN,4,1,247.0
27,15.0,800.0,800.0,NaN,NaN,4,2,246.0
28,7.0,NaN,NaN,NaN,NaN,4,1,246.0
29,11.0,6000.0,6000.0,NaN,NaN,16,1,246.0
...,...,...,...,...,...,...,...,...
362421,15.0,2300.0,2300.0,NaN,NaN,16,1,292.0
362422,11.0,NaN,NaN,NaN,NaN,4,2,292.0
362423,15.0,6500.0,6500.0,NaN,NaN,16,1,292.0
362424,15.0,6000.0,6000.0,NaN,NaN,2,1,292.0
362425,15.0,3000.0,3000.0,NaN,NaN,16,2,293.0
362426,15.0,4000.0,4000.0,NaN,NaN,4,2,292.0
362427,15.0,10000.0,7200.0,NaN,NaN,16,2,293.0
362428,5.0,1400.0,NaN,NaN,NaN,16,2,293.0
362429,11.0,3000.0,3000.0,NaN,NaN,16,1,293.0
362430,15.0,1800.0,1800.0,NaN,NaN,16,2,292.0
362431,15.0,8000.0,8000.0,NaN,NaN,16,1,293.0
362432,15.0,6000.0,6000.0,NaN,NaN,16,2,293.0
362433,7.0,NaN,NaN,NaN,NaN,16,2,292.0
362434,4.0,NaN,NaN,NaN,NaN,16,1,292.0
362435,15.0,16000.0,16000.0,NaN,NaN,16,1,292.0
362436,15.0,8500.0,8500.0,NaN,NaN,16,2,293.0
362437,0.0,NaN,NaN,NaN,NaN,16,1,292.0
362438,8.0,NaN,NaN,NaN,NaN,16,1,292.0
362439,15.0,14000.0,14000.0,NaN,NaN,16,2,292.0
362440,15.0,7000.0,7000.0,NaN,NaN,16,1,292.0
362441,11.0,3000.0,3000.0,NaN,NaN,16,1,292.0
362442,11.0,3000.0,3000.0,NaN,NaN,16,2,292.0
362443,15.0,1400.0,1400.0,NaN,NaN,4,1,292.0
362444,11.0,NaN,NaN,NaN,NaN,16,1,293.0
362445,5.0,NaN,NaN,NaN,NaN,16,2,292.0
362446,15.0,NaN,NaN,NaN,NaN,16,2,292.0
362447,12.0,20000.0,20000.0,NaN,NaN,16,1,292.0
362448,13.0,NaN,NaN,NaN,NaN,16,1,292.0
362449,13.0,NaN,NaN,NaN,NaN,16,1,292.0
362450,15.0,13000.0,13000.0,NaN,NaN,16,1,292.0

### Gênero
Sabe-se que existem mais mulheres que homens no Brasil, logo, como a tabela representa a população brasileira então 1 representa a população masculina e 2 a população feminina.

1. **Homens**
2. **Mulheres**

In [25]:
data[data.gender == 1].sum()['weight']

97180709.0

In [26]:
data[data.gender == 2].sum()['weight']

102508198.0

### Raça

Por comparação entre os números absolutos dos dados e a tabela https://sidra.ibge.gov.br/Tabela/3175#resultado, temos que:

0. Sem declaração
1. Amarela
2. Preto
4. Pardo
8. Indígena
16. Branco

In [27]:
data.race.unique()

array([16,  2,  4,  1,  8,  0])

In [21]:
# Sem declaração
data[data.race == 0].sum()['weight']

6481.0

In [16]:
# Amarela
data[data.race == 1].sum()['weight']

1031978.0

In [17]:
# Preto
data[data.race == 2].sum()['weight']

15862257.0

In [18]:
# Pardo
data[data.race == 4].sum()['weight']

89776808.0

In [19]:
# Indígena
data[data.race == 8].sum()['weight']

596832.0

In [29]:
# Branco
data[data.race == 16].sum()['weight']

92414551.0